Feature/kb 37 impl basic table
Taehoya/taste-dictionary-server pull request #27
Opened 2023-08-27 07:37 UTC by homekeeper89

# 설명
- 최초 DDL 구현
- postgis 적용을 위한 image 변경
- #ISSUE
-

# 테스트

-

2023-08-27 12:39 UTC, Taehoya requested changes

2023-08-27 12:39 UTC, Taehoya commented on prisma/migrations/20230827073521_init_tables/migration.sql
> +CREATE TABLE "users" (
`IF NOT EXISTS`를 추가해주실 수 있을까요? -> `CREATE TABLE IF NOT EXISTS users`
- 나중에 테이블 초기화하거나 업데이트 할때 문제가 생기는거를 방지해주기 때문에 있으면 좋을거 같습니다.
- https://www.commandprompt.com/education/postgresql-create-table-if-not-exists/

2023-08-27 12:39 UTC, Taehoya commented on prisma/migrations/20230827073521_init_tables/migration.sql
> +CREATE INDEX "users_nickname_idx" ON "users"("nickname");
index가 조금 많은 거 같은데 혹시 설명을 해주실 수 있을까요?

2023-08-28 14:28 UTC, homekeeper89 commented on prisma/migrations/20230827073521_init_tables/migration.sql
> +CREATE INDEX "users_nickname_idx" ON "users"("nickname");
검색 가능한 모든 것들 다 넣었다 보시면 될것 같아요

2023-08-28 14:29 UTC, homekeeper89 commented on prisma/migrations/20230827073521_init_tables/migration.sql
> +CREATE TABLE "users" (
마이그레이션이 순서에 맞춰 진행되는 거라서 과거의 것이 적용되는 건 걱정 안해도 될것 같아요 😄

2023-08-28 15:11 UTC, Taehoya approved these changes

2023-08-29 13:01 UTC, merged